import { getVideosFromPlaylist, initYoutube, updateVideo, updateVideoThumbnail } from './utils/youtubeAPI.js'
import { joinYoutubeAndOpenPlannerData } from './utils/joinYoutubeAndOpenPlannerData.js'
import { getOpenPlannerContent } from './utils/getOpenPlannerContent.js'
import 'dotenv/config'

// Thumbnails are keyed by session id and produced by youtube-thumbnails/generateThumbnails.ts.
// Override with the THUMBNAILS_DIR env var if you keep them elsewhere.
const THUMBNAILS_DIR = process.env.THUMBNAILS_DIR || `./youtube-thumbnails/output/${process.env.OPENPLANNER_EVENT_ID}`

/**
 * This script allow for batch edit of youtube metadata (title, desc, tags, date, thumbnail).
 * The youtube video should be uploaded separately with the title matching the one from OpenPlanner.
 *
 * It can update:
 * - title
 * - description (it will format the author name + social links + abstract)
 * - tags
 * - recorded date
 * - thumbnail from thumbnails generated by youtube-thumbnails/generateThumbnails.ts (or your own), keyed by the session id from OpenPlanner (e.g. <sessionId>.jpg)
 *
 * Pre-requisites:
 * - Upload videos to youtube with the same (title or id) as in OpenPlanner
 * - Generate thumbnails: cd scripts && npx tsx youtube-thumbnails/generateThumbnails.ts --json <dataUrl>. They land in youtube-thumbnails/output/<eventId>/<sessionId>.jpg, which is where this script reads them from (override with the THUMBNAILS_DIR env var).
 * - change the playlist id "playlistId" to the one you want to edit (create it on youtube first)
 * - get the full data from open planner as "openplanner.json" in scripts/openplanner.json
 * - get the `scripts/client_secret.json` from https://console.developers.google.com/
 * - node 24
 *
 * Usage:
 * - cd scripts
 * - npm install
 * - node youtubeBatchEdit.js
 *
 * Help:
 * - the youtube credential code looks like 4/0AcvDMrBXVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx in the url
 */

const formatYoutubeDescription = (video, openPlannerContent) => {
    const { session, speakers } = video

    if (!session) {
        return null
    }

    const speakersText = speakers.map((speaker) => {
        const socialLink = speaker.socials.map((social) => {
            if (!social.link) {
                return ''
            }
            if (social.link.startsWith('http')) {
                return social.link
            }
            const accountName = social.link.replace('@', '')
            if (social.name === 'Twitter') {
                return `https://twitter.com/${accountName}`
            }
            if (social.name === 'X') {
                return `https://x.com/${accountName}`
            }
            if (social.name === 'Linkedin') {
                return `https://linkedin.com/in/${accountName}`
            }
            if (social.name === 'GitHub') {
                return `https://github.com/${accountName}`
            }
        })[0]
        if (!socialLink) {
            return speaker.name
        }
        return `${speaker.name} - ${socialLink}`
    })

    const desc = session.abstract + '\n\n' + openPlannerContent.event.name

    const cleaned = `${speakersText.join('\n')}\n${desc}`
        .replace(/<[^>]*>/g, '') // strip HTML tags
        .replace(/[<>]/g, '') // YouTube rejects any remaining angle brackets

    // YouTube caps descriptions at 5000 characters
    return cleaned.length > 5000 ? cleaned.slice(0, 4997) + '...' : cleaned
}

const main = async () => {
    const { auth, channelId } = await initYoutube()

    const playlistId = process.env.YOUTUBE_PLAYLIST_ID
    const openPlannerEventId = process.env.OPENPLANNER_EVENT_ID

    const openPlannerContent = await getOpenPlannerContent(openPlannerEventId)
    const videoCategoryId = '27' // use await listVideoCategories(auth)

    const videos = await getVideosFromPlaylist(auth, channelId, playlistId)

    console.log('Retrieved videos: ' + videos.length)

    const videosWithValidSession = joinYoutubeAndOpenPlannerData(videos, openPlannerContent)

    // Optional: restrict the run to specific session titles passed as CLI args
    // e.g. node youtube/youtubeBatchEdit.js "Title one" "Title two"
    const titleFilter = process.argv.slice(2)

    const videosWithValidSessionAndDescription = videosWithValidSession
        .filter((video) => titleFilter.length === 0 || titleFilter.some((title) => video.session.title === title))
        .map((video) => {
            return {
                ...video,
                description: formatYoutubeDescription(video, openPlannerContent),
            }
        })
        .filter((video) => !!video)

    if (titleFilter.length > 0) {
        console.log(
            `Filtering to ${titleFilter.length} title(s): matched ${videosWithValidSessionAndDescription.length} video(s)`
        )
    }

    // Update video metadata
    for (const video of videosWithValidSessionAndDescription) {
        const tagBasedOnOpenPlannerCategory = openPlannerContent.event.categories.find((category) => {
            return category.id === video.session.categoryId
        })?.name

        // Derive the year from the session recording date, not the current date, so re-running
        // for a past event in a later year still tags the correct year.
        const eventYear = (video.session.dateStart ? new Date(video.session.dateStart) : new Date()).getFullYear()

        const updateModel = {
            description: video.description,
            categoryId: videoCategoryId,
            defaultLanguage: 'fr',
            tags: ['sunnytech', tagBasedOnOpenPlannerCategory, 'sunnytech-' + eventYear].filter(Boolean),
            recordingDetails: {
                recordingDate: video.session.dateStart,
            },
        }

        const videoId = video.snippet.resourceId.videoId
        // YouTube rejects titles containing < or >, and caps them at 100 characters.
        const cleanTitle = video.session.title.replace(/[<>]/g, '')
        const videoTitle = cleanTitle.length > 100 ? cleanTitle.slice(0, 97) + '...' : cleanTitle
        if (cleanTitle.length > 100) {
            console.log(
                ' ⚠️ Video title is too long and has been sliced: ' +
                    video.session.title +
                    ' (YT video id: ' +
                    videoId +
                    ')',
                video.session.videoLink
            )
        }
        const result = await updateVideo(auth, videoId, videoTitle, updateModel)
        if (result) {
            console.log('Updated video: ' + video.snippet.title)
        }
    }

    // Update video thumbnails. File name is the session id, matching the output of
    // youtube-thumbnails/generateThumbnails.ts (see THUMBNAILS_DIR below).
    for (const video of videosWithValidSessionAndDescription) {
        const thumbnailPath = `${THUMBNAILS_DIR}/${video.session.id}.jpg`
        const videoId = video.snippet.resourceId.videoId

        console.log('Updating video thumbnail for ' + video.session.title + ' (YT video id: ' + videoId + ')')

        try {
            const result = await updateVideoThumbnail(auth, videoId, thumbnailPath)
            if (result) {
                console.log('Updated video thumbnail: ' + video.snippet.title)
            }
        } catch (error) {
            console.error(`❌ Failed to set thumbnail for ${videoId} (${video.session.title}): ${error.message}`)
        }
    }
}

main()
