import { Dialog, DialogContent, DialogTitle, Grid, Typography } from '@mui/material'
import { FormContainer, useForm } from 'react-hook-form-mui'
import LoadingButton from '@mui/lab/LoadingButton'
import { doc } from 'firebase/firestore'
import { Event, SpeakerCustomField } from '../../../../types'
import { collections } from '../../../../services/firebase'
import { useFirestoreDocumentMutation } from '../../../../services/hooks/firestoreMutationHooks'
import { SpeakerCustomFieldsFields } from '../../settings/components/SpeakerCustomFieldsFields'
import { slugify } from '../../../../utils/slugify'

export type SpeakerCustomFieldsDialogProps = {
    event: Event
    open: boolean
    onClose: () => void
}

export const SpeakerCustomFieldsDialog = ({ event, open, onClose }: SpeakerCustomFieldsDialogProps) => {
    const mutation = useFirestoreDocumentMutation(doc(collections.events, event.id))

    const formContext = useForm<{ speakerCustomFields: SpeakerCustomField[] }>({
        defaultValues: {
            speakerCustomFields: event.speakerCustomFields || [],
        },
    })
    const { control, formState } = formContext

    return (
        <Dialog open={open} onClose={onClose} fullWidth maxWidth="md">
            <DialogTitle>Speaker custom fields</DialogTitle>
            <DialogContent>
                <FormContainer
                    formContext={formContext}
                    onSuccess={async (data) => {
                        const raw: SpeakerCustomField[] = (data.speakerCustomFields || [])
                            .filter((field) => field.name && field.name.trim().length > 0)
                            .map((field) => ({
                                name: field.name.trim(),
                                type: field.type,
                                privacy: field.privacy || 'public',
                                id: field.id.startsWith('autogenerated-') ? slugify(field.name.trim()) : field.id,
                            }))
                        const speakerCustomFields = [...new Map(raw.map((f) => [f.id, f])).values()]
                        await mutation.mutate({ speakerCustomFields })
                        onClose()
                    }}>
                    <SpeakerCustomFieldsFields control={control} isSubmitting={formState.isSubmitting} />

                    <Grid item xs={12}>
                        <LoadingButton
                            type="submit"
                            disabled={formState.isSubmitting}
                            loading={formState.isSubmitting}
                            fullWidth
                            variant="contained"
                            sx={{ mt: 2, mb: 2 }}>
                            Save
                        </LoadingButton>
                        {mutation.error && <Typography color="error">{mutation.error.message}</Typography>}
                    </Grid>
                </FormContainer>
            </DialogContent>
        </Dialog>
    )
}
