import * as React from 'react'
import { Box, IconButton, Typography } from '@mui/material'
import { Control, TextFieldElement, useFieldArray } from 'react-hook-form-mui'
import { Add, Delete } from '@mui/icons-material'
import { Category, EventForForm } from '../../../../types'

export type CategoriesFieldsProps = {
    control: Control<EventForForm, any>
    isSubmitting: boolean
}
type CategoryWithKey = Category & { key: string }
export const CategoriesFields = ({ control, isSubmitting }: CategoriesFieldsProps) => {
    const { fields, append, remove } = useFieldArray({
        control,
        name: 'categories',
        keyName: 'key',
    })

    return (
        <>
            <Typography fontWeight="600" mt={2}>
                Categories
            </Typography>

            <Box paddingLeft={2}>
                {fields.map((category: CategoryWithKey, index) => (
                    <Box display="flex" key={category.key}>
                        <TextFieldElement
                            id={category.key}
                            label={`id: ${category.id}`}
                            name={`categories.${index}.name`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                        />

                        <IconButton
                            aria-label="Remove category"
                            onClick={() => {
                                remove(index)
                            }}
                            edge="end">
                            <Delete />
                        </IconButton>
                    </Box>
                ))}
                <IconButton
                    aria-label="Add category"
                    onClick={() => {
                        append({
                            id: `autogenerated-${Date.now()}`,
                            name: '',
                        })
                    }}>
                    <Add />
                </IconButton>
            </Box>
        </>
    )
}
