import * as React from 'react'
import { Box, IconButton, Typography } from '@mui/material'
import { Control, TextFieldElement, SelectElement, useFieldArray } from 'react-hook-form-mui'
import { Add, Delete } from '@mui/icons-material'

export type SpeakerCustomFieldsFieldsProps = {
    control: Control<any, any>
    isSubmitting: boolean
}

export const SpeakerCustomFieldsFields = ({ control, isSubmitting }: SpeakerCustomFieldsFieldsProps) => {
    const { fields, append, remove } = useFieldArray({
        control,
        name: 'speakerCustomFields',
        keyName: 'key',
    })

    return (
        <>
            <Typography fontWeight="600" mt={2}>
                Speaker custom fields
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                Define custom fields available on every speaker. Public fields appear in the published JSON; private
                fields only appear in the private JSON export.
            </Typography>

            <Box paddingLeft={2}>
                {fields.map((field, index) => (
                    <Box display="flex" key={field.key} alignItems="center" gap={1}>
                        <TextFieldElement
                            label="Field name"
                            name={`speakerCustomFields.${index}.name`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                            helperText={!field.id.startsWith('autogenerated-') ? `id: ${field.id}` : undefined}
                        />
                        <SelectElement
                            label="Type"
                            name={`speakerCustomFields.${index}.type`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                            options={[
                                { id: 'text', label: 'Text' },
                                { id: 'boolean', label: 'Boolean' },
                            ]}
                            sx={{ minWidth: 120 }}
                        />
                        <SelectElement
                            label="Privacy"
                            name={`speakerCustomFields.${index}.privacy`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                            options={[
                                { id: 'public', label: 'Public' },
                                { id: 'private', label: 'Private' },
                            ]}
                            sx={{ minWidth: 120 }}
                        />
                        <IconButton
                            aria-label="Remove custom field"
                            onClick={() => {
                                remove(index)
                            }}
                            edge="end">
                            <Delete />
                        </IconButton>
                    </Box>
                ))}
                <IconButton
                    aria-label="Add speaker custom field"
                    onClick={() => {
                        append({
                            id: `autogenerated-${Date.now()}`,
                            name: '',
                            type: 'text',
                            privacy: 'public',
                        })
                    }}>
                    <Add />
                </IconButton>
            </Box>
        </>
    )
}
