import * as React from 'react'
import { Box, IconButton, Typography } from '@mui/material'
import { Control, TextFieldElement, SelectElement, useFieldArray } from 'react-hook-form-mui'
import { Add, Delete } from '@mui/icons-material'
import { SponsorCustomField } from '../../../../types'

type SponsorCustomFieldsForm = { sponsorCustomFields: SponsorCustomField[] }

export type SponsorCustomFieldsFieldsProps = {
    control: Control<any, any>
    isSubmitting: boolean
}

export const SponsorCustomFieldsFields = ({ control, isSubmitting }: SponsorCustomFieldsFieldsProps) => {
    const { fields, append, remove } = useFieldArray<SponsorCustomFieldsForm, 'sponsorCustomFields', 'key'>({
        control: control as Control<SponsorCustomFieldsForm>,
        name: 'sponsorCustomFields',
        keyName: 'key',
    })

    return (
        <>
            <Typography fontWeight="600" mt={2}>
                Sponsor custom fields
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                Define custom fields that will be available on every sponsor. These fields will also appear in the
                published JSON.
            </Typography>

            <Box paddingLeft={2}>
                {fields.map((field, index) => (
                    <Box display="flex" key={field.key} alignItems="flex-start" gap={1}>
                        <TextFieldElement
                            label="Field name"
                            name={`sponsorCustomFields.${index}.name`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                            helperText={!field.id.startsWith('autogenerated-') ? `id: ${field.id}` : undefined}
                        />
                        <SelectElement
                            label="Type"
                            name={`sponsorCustomFields.${index}.type`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                            options={[
                                { id: 'text', label: 'Text' },
                                { id: 'boolean', label: 'Boolean' },
                            ]}
                            sx={{ minWidth: 120 }}
                        />
                        <IconButton
                            aria-label="Remove custom field"
                            onClick={() => {
                                remove(index)
                            }}
                            edge="end">
                            <Delete />
                        </IconButton>
                    </Box>
                ))}
                <IconButton
                    aria-label="Add sponsor custom field"
                    onClick={() => {
                        append({
                            id: `autogenerated-${Date.now()}`,
                            name: '',
                            type: 'text',
                        })
                    }}>
                    <Add />
                </IconButton>
            </Box>
        </>
    )
}
