import * as React from 'react'
import { Box, IconButton, Typography } from '@mui/material'
import { Control, TextFieldElement, useFieldArray } from 'react-hook-form-mui'
import { Add, Delete } from '@mui/icons-material'
import { Event, Track } from '../../../../types'

export type TrackFieldsProps = {
    control: Control<Event, any>
    isSubmitting: boolean
}
type TrackWithKey = Track & { key: string }
export const TrackFields = ({ control, isSubmitting }: TrackFieldsProps) => {
    const { fields, append, remove } = useFieldArray({
        control,
        name: 'tracks',
        keyName: 'key',
    })

    return (
        <>
            <Typography fontWeight="600" mt={2}>
                Tracks
            </Typography>

            <Box paddingLeft={2}>
                {fields.map((track: TrackWithKey, index) => (
                    <Box display="flex" key={track.key}>
                        <TextFieldElement
                            id={track.key}
                            label={`id: ${track.id}`}
                            name={`tracks.${index}.name`}
                            control={control}
                            variant="filled"
                            size="small"
                            margin="dense"
                            disabled={isSubmitting}
                        />

                        <IconButton
                            aria-label="Remove track"
                            onClick={() => {
                                remove(index)
                            }}
                            edge="end">
                            <Delete />
                        </IconButton>
                    </Box>
                ))}
                <IconButton
                    aria-label="Add track"
                    onClick={() => {
                        append({
                            id: `autogenerated-${Date.now()}`,
                            name: '',
                        })
                    }}>
                    <Add />
                </IconButton>
            </Box>
        </>
    )
}
