export type PublicFaqItemType = {
    id: string
    question: string
    answer: string
    order: number
}

export type PublicFaqCategoryType = {
    id: string
    name: string
    order: number
    faqs: PublicFaqItemType[]
    unifiedPage: boolean
}

export type PublicFaqType = {
    category: PublicFaqCategoryType
    questions: PublicFaqItemType[]
}

export type PublicFaqReply = {
    faq: PublicFaqType[]
    eventName: string
}

export type TranscriptionReply = {
    eventName: string
    gladiaAPIKey: string
    dataUrl: string
}

// This represents the Static Public JSON generated by OpenPlanner
export type PublicJSON = {
    event: {
        name?: string
        language?: string | null
        tracks: {
            id: string
            name: string
        }[]
        categories?: {
            id: string
            name: string
            color?: string | null
        }[]
        intermissionMediaUrl?: string | null
    }
    speakers?: {
        id: string
        name: string
    }[]
    sessions: {
        id: string
        trackId: string
        dateStart: string
        dateEnd: string
        speakersIds?: string[]
        speakerIds?: string[]
        title: string
        abstract: []
        showInFeedback: boolean
        categoryId?: string | null
    }[]
}
